"""IsolationForest sidecar for excessive_api — complements Rule 5.

- Additive: existing 5 rules in detector.py still run. This adds an ML alert
  when the feature vector is anomalous, even if count <= threshold.
- Fallback-safe: if model missing or sklearn not installed, returns [].
- Model path: <repo>/ml/model.pkl (gitignored, generated by scripts/train.py).
"""
import os
from datetime import datetime, timezone

from .config import RISK_SCORES
from .mitre import technique, recommendation
from .ml_features import featurize

MODEL_PATH = os.path.join(os.path.dirname(__file__), "..", "ml", "model.pkl")
_model = None  # loaded IsolationForest or None


def _load_model():
    global _model
    if not os.path.exists(MODEL_PATH):
        _model = None
        return None
    try:
        import joblib

        _model = joblib.load(MODEL_PATH)
        return _model
    except Exception:
        _model = None
        return None


def load():
    """Called at app startup. Safe to call multiple times."""
    return _load_model()


def is_ready() -> bool:
    return _model is not None and os.path.exists(MODEL_PATH)


def get_status() -> dict:
    return {
        "ready": is_ready(),
        "model_path": os.path.abspath(MODEL_PATH) if os.path.exists(MODEL_PATH) else None,
        "model_exists": os.path.exists(MODEL_PATH),
    }


def ml_detect(event: dict, event_id: int, recent_events: list) -> list:
    """Return ML alert if anomaly, else []. Never raises."""
    if _model is None:
        # lazy try load once
        if not os.path.exists(MODEL_PATH):
            return []
        _load_model()
        if _model is None:
            return []

    try:
        feats = featurize(event, recent_events)
        # IsolationForest: decision_function < 0 means anomaly; predict == -1
        import numpy as np

        X = np.array([feats], dtype=float)
        pred = _model.predict(X)[0]  # 1 normal, -1 anomaly
        score = float(_model.decision_function(X)[0])  # negative = more anomalous
        # also consider score threshold for borderline
        if pred == -1:
            # build alert — same shape as detector._alert but tagged ml_anomaly
            return [
                {
                    "event_id": event_id,
                    "title": "Anomalous API Activity (ML)",
                    "description": (
                        f"ML detected anomalous activity by {event.get('user','unknown')} "
                        f"(anomaly score {score:.3f}). Features: count_60s={feats[0]:.0f}, "
                        f"hour={int(feats[1]*23):02d}:00, off_hours={int(feats[2])}, "
                        f"ip_changed={int(feats[3])}, diversity={feats[4]:.2f}."
                    ),
                    "severity": "HIGH",
                    "risk_score": RISK_SCORES.get("excessive_api", 80),
                    "mitre_technique": technique("excessive_api"),
                    "recommendation": recommendation("excessive_api")
                    + " (ML: review off-hours / IP change).",
                    "created_at": datetime.now(timezone.utc).isoformat(),
                    "status": "OPEN",
                    "_rule": "ml_anomaly",
                    "_ml_score": score,
                    "_ml_features": feats,
                }
            ]
        return []
    except Exception:
        # never break event collection on ML failure — ponytail: fail open
        return []
